# Generated by Django 5.0.2 on 2024-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Book',
            fields=[
                ('Barcode', models.IntegerField(primary_key='Barcode', serialize=False)),
                ('Book_Title', models.CharField(max_length=25)),
                ('Author_Name', models.CharField(max_length=25)),
                ('Author_email', models.EmailField(max_length=254)),
                ('DoP', models.DateField()),
                ('Pages', models.IntegerField()),
            ],
        ),
    ]
